image: "rust:latest"

test:linux:
  script:
  - cargo check --examples

test:mac:
  script:
  - rustup target add x86_64-apple-darwin
  - cargo check --target x86_64-apple-darwin --examples

test:redox:
  script:
  - rustup install nightly
  - rustup target add x86_64-unknown-redox --toolchain nightly
  - cargo +nightly check --target x86_64-unknown-redox --examples
